const PDFDocument = require('pdfkit')
const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
)

async function exportToPdf(analysisId, userId) {
  // Get the analysis
  const { data: analysis, error } = await supabase
    .from('contract_analyses')
    .select('*')
    .eq('id', analysisId)
    .eq('user_id', userId)
    .single()

  if (error || !analysis) {
    throw new Error('Analysis not found')
  }

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 })
      const chunks = []

      doc.on('data', chunk => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // Title
      doc.fontSize(24).font('Helvetica-Bold').text('Contract Analysis Report', { align: 'center' })
      doc.moveDown()

      // Metadata
      doc.fontSize(12).font('Helvetica')
      doc.text(`Filename: ${analysis.filename}`)
      doc.text(`Analysis Date: ${new Date(analysis.created_at).toLocaleDateString()}`)
      doc.text(`Pages: ${analysis.pages || 'N/A'}`)
      doc.moveDown()

      // Overall Risk
      const riskColors = {
        low: 'green',
        medium: 'orange',
        high: 'red',
      }
      doc.fontSize(16).font('Helvetica-Bold')
      doc.fillColor(riskColors[analysis.analysis.overallRisk] || 'black')
      doc.text(`Overall Risk: ${analysis.analysis.overallRisk.toUpperCase()}`)
      doc.fillColor('black')
      doc.moveDown()

      // Summary
      doc.fontSize(14).font('Helvetica-Bold').text('Summary')
      doc.fontSize(12).font('Helvetica').text(analysis.analysis.summary || 'No summary available')
      doc.moveDown()

      // Parties
      if (analysis.analysis.parties && analysis.analysis.parties.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Parties')
        doc.fontSize(12).font('Helvetica')
        analysis.analysis.parties.forEach(party => {
          doc.text(`• ${party}`)
        })
        doc.moveDown()
      }

      // Contract Type
      if (analysis.analysis.contractType) {
        doc.fontSize(14).font('Helvetica-Bold').text('Contract Type')
        doc.fontSize(12).font('Helvetica').text(analysis.analysis.contractType)
        doc.moveDown()
      }

      // Key Dates
      if (analysis.analysis.keyDates && analysis.analysis.keyDates.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Key Dates')
        doc.fontSize(12).font('Helvetica')
        analysis.analysis.keyDates.forEach(date => {
          doc.text(`• ${date.label}: ${date.value}`)
        })
        doc.moveDown()
      }

      // Red Flags
      if (analysis.analysis.redFlags && analysis.analysis.redFlags.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').fillColor('red').text('Red Flags')
        doc.fillColor('black')
        doc.fontSize(12).font('Helvetica')
        analysis.analysis.redFlags.forEach(flag => {
          doc.text(`⚠ ${flag}`)
        })
        doc.moveDown()
      }

      // Clauses
      if (analysis.analysis.clauses && analysis.analysis.clauses.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Clause Analysis')
        doc.moveDown()

        analysis.analysis.clauses.forEach((clause, index) => {
          const clauseRiskColors = {
            low: 'green',
            medium: 'orange',
            high: 'red',
          }

          doc.fontSize(12).font('Helvetica-Bold')
          doc.fillColor(clauseRiskColors[clause.riskLevel] || 'black')
          doc.text(`${index + 1}. ${clause.title} (${clause.riskLevel.toUpperCase()})`)
          doc.fillColor('black')

          doc.fontSize(11).font('Helvetica').text(clause.summary)
          
          if (clause.riskReason) {
            doc.fontSize(10).font('Helvetica-Oblique').fillColor('gray').text(`Risk: ${clause.riskReason}`)
            doc.fillColor('black')
          }
          doc.moveDown()
        })
      }

      // Recommendations
      if (analysis.analysis.recommendations && analysis.analysis.recommendations.length > 0) {
        doc.fontSize(14).font('Helvetica-Bold').text('Recommendations')
        doc.fontSize(12).font('Helvetica')
        analysis.analysis.recommendations.forEach(rec => {
          doc.text(`• ${rec}`)
        })
        doc.moveDown()
      }

      // Footer
      doc.fontSize(10).font('Helvetica-Oblique')
      doc.text(
        'Generated by ContractLens - AI-powered contract analysis',
        { align: 'center' }
      )

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

async function exportToJson(analysisId, userId) {
  // Get the analysis
  const { data: analysis, error } = await supabase
    .from('contract_analyses')
    .select('*')
    .eq('id', analysisId)
    .eq('user_id', userId)
    .single()

  if (error || !analysis) {
    throw new Error('Analysis not found')
  }

  // Return the analysis data as JSON
  return {
    id: analysis.id,
    filename: analysis.filename,
    pages: analysis.pages,
    createdAt: analysis.created_at,
    analysis: analysis.analysis,
  }
}

module.exports = {
  exportToPdf,
  exportToJson,
}
